version: '2.1' # due to extends
services:
  rails:
    build:
      context: .
    image: rails
    volumes:
      - .:/web
    ports:
      - 3000:3000
    entrypoint:
      - bash
      - --login
  rails-test:
    extends: rails
    build:
      context: .
      dockerfile: sdlc/Dockerfile.rails-test
    image: rails-test
    shm_size: 128M
    entrypoint:
      - bash
      - --login
  rails-test-run:
    image: rails-test
    entrypoint:
      - bash
      - --login
      - xvfb-run
      - rails
      - test:system
      - RAILS_ENV=test
