version: '2.1' # due to extends
services:
  rails:
    build:
      context: .
    image: rails
    read_only: true
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 20
    environment:
      - RAILS_ENV=development
    networks:
      railsnet:
        aliases:
          - rails

  rails2:
    image: rails
    read_only: true
    depends_on:
      rails:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 20
    environment:
      - RAILS_ENV=development
    networks:
      railsnet:
        aliases:
          - rails2

  caddy:
    image: hammer098/caddy_rails:latest
    depends_on:
      - rails2
    ports:
      - 443:443
    read_only: true
    environment:
      - TZ=America/New_York
    networks:
      - railsnet

networks:
  railsnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
