version: '2.1' # due to extends
services:
  rails-raw:
    build:
      context: .
    image: rails-raw
    volumes:
      - .:/web
    ports:
      - 3000:3000
    entrypoint:
      - bash
      - --login
  rails-test:
    extends: rails-raw
    build:
      context: test/
      dockerfile: Dockerfile
    image: rails-test
    shm_size: 128M
    entrypoint:
      - bash
      - --login
